/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OptimizeCanvasConnectionsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var ALL_SIDES = ["top", "bottom", "left", "right"];
var DEFAULT_SETTINGS = {
  allowedOutgoingSides: [...ALL_SIDES],
  allowedIncomingSides: [...ALL_SIDES]
};
var SIDE_LABELS = {
  top: "Top",
  bottom: "Bottom",
  left: "Left",
  right: "Right"
};
var OptimizeCanvasConnectionsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app2, plugin) {
    super(app2, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h3", { text: "Allowed sides" });
    containerEl.createEl("p", {
      text: "Restrict which sides of a node the optimizer is allowed to use. Outgoing controls the side an edge leaves its source node from; incoming controls the side an edge arrives at its target node from. If none of a node's allowed sides fit the current optimization mode, the optimizer falls back to the closest allowed side.",
      cls: "setting-item-description"
    });
    containerEl.createEl("h4", { text: "Allowed outgoing sides" });
    containerEl.createEl("p", {
      text: "Sides an edge may leave its source node from.",
      cls: "setting-item-description"
    });
    this.addSideToggles("allowedOutgoingSides");
    containerEl.createEl("h4", { text: "Allowed incoming sides" });
    containerEl.createEl("p", {
      text: "Sides an edge may arrive at its target node from.",
      cls: "setting-item-description"
    });
    this.addSideToggles("allowedIncomingSides");
  }
  addSideToggles(key) {
    for (const side of ALL_SIDES) {
      new import_obsidian.Setting(this.containerEl).setName(SIDE_LABELS[side]).addToggle((toggle) => toggle.setValue(this.plugin.settings[key].includes(side)).onChange(async (value) => {
        const sides = this.plugin.settings[key];
        if (value && !sides.includes(side)) {
          sides.push(side);
        } else if (!value) {
          const idx = sides.indexOf(side);
          if (idx !== -1)
            sides.splice(idx, 1);
        }
        await this.plugin.saveSettings();
      }));
    }
  }
};

// main.ts
var OptimizeCanvasConnectionsPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    this.addSettingTab(new OptimizeCanvasConnectionsSettingTab(this.app, this));
    this.addCommand({
      id: "optimize-preserve-axes-selection",
      name: "Optimize selection (preserve axes)",
      checkCallback: (checking) => {
        const canvasView = app.workspace.getActiveViewOfType(import_obsidian2.ItemView);
        if ((canvasView == null ? void 0 : canvasView.getViewType()) == "canvas") {
          if (!checking) {
            this.optimize("preserve-axes");
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "optimize-shortest-path-selection",
      name: "Optimize selection (shortest path)",
      checkCallback: (checking) => {
        const canvasView = app.workspace.getActiveViewOfType(import_obsidian2.ItemView);
        if ((canvasView == null ? void 0 : canvasView.getViewType()) == "canvas") {
          if (!checking) {
            this.optimize("shortest-path");
          }
          return true;
        }
        return false;
      }
    });
  }
  onunload() {
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // Narrow a list of candidate sides down to the ones the user has allowed
  // (settings) for that edge end. Falls back to the unfiltered candidates
  // (then to all 4 sides) if that leaves nothing usable, so a fully
  // unchecked setting or an incompatible combination never breaks the
  // optimizer.
  applyAllowedSides(candidates, allowed) {
    const filtered = candidates.filter((side) => allowed.includes(side));
    if (filtered.length > 0)
      return filtered;
    if (allowed.length > 0)
      return allowed;
    return ALL_SIDES;
  }
  async optimize(option) {
    const canvasView = app.workspace.getActiveViewOfType(import_obsidian2.ItemView);
    const canvas = canvasView == null ? void 0 : canvasView.canvas;
    const currentSelection = canvas == null ? void 0 : canvas.selection;
    let selectedIDs = new Array();
    currentSelection.forEach(function(selection) {
      selectedIDs.push(selection.id);
    });
    let applyToAll = false;
    if (selectedIDs.length == 0) {
      applyToAll = true;
    }
    for (let [edgeKey, edge] of canvas["edges"]) {
      let fromNode = edge["from"]["node"];
      let toNode = edge["to"]["node"];
      let fromPossibilities = [edge["from"]["side"]];
      if (applyToAll || selectedIDs.includes(fromNode["id"])) {
        switch (option) {
          case "shortest-path":
            fromPossibilities = ["top", "bottom", "left", "right"];
            break;
          case "preserve-axes":
            switch (edge["from"]["side"]) {
              case "top":
              case "bottom":
                fromPossibilities = ["top", "bottom"];
                break;
              case "left":
              case "right":
                fromPossibilities = ["left", "right"];
                break;
            }
        }
        fromPossibilities = this.applyAllowedSides(fromPossibilities, this.settings.allowedOutgoingSides);
      }
      let toPossibilities = [edge["to"]["side"]];
      if (applyToAll || selectedIDs.includes(toNode["id"])) {
        switch (option) {
          case "shortest-path":
            toPossibilities = ["top", "bottom", "left", "right"];
            break;
          case "preserve-axes":
            switch (edge["to"]["side"]) {
              case "top":
              case "bottom":
                toPossibilities = ["top", "bottom"];
                break;
              case "left":
              case "right":
                toPossibilities = ["left", "right"];
                break;
            }
        }
        toPossibilities = this.applyAllowedSides(toPossibilities, this.settings.allowedIncomingSides);
      }
      let distances = [];
      for (const fromSide of fromPossibilities) {
        let fromPoint = { "x": 0, "y": 0 };
        if (fromSide == "top") {
          fromPoint = { "x": fromNode["x"] + fromNode["width"] / 2, "y": fromNode["y"] };
        } else if (fromSide == "bottom") {
          fromPoint = { "x": fromNode["x"] + fromNode["width"] / 2, "y": fromNode["y"] + fromNode["height"] };
        } else if (fromSide == "left") {
          fromPoint = { "x": fromNode["x"], "y": fromNode["y"] + fromNode["height"] / 2 };
        } else if (fromSide == "right") {
          fromPoint = { "x": fromNode["x"] + fromNode["width"], "y": fromNode["y"] + fromNode["height"] / 2 };
        }
        for (const toSide of toPossibilities) {
          let toPoint = { "x": 0, "y": 0 };
          if (toSide == "top") {
            toPoint = { "x": toNode["x"] + toNode["width"] / 2, "y": toNode["y"] };
          } else if (toSide == "bottom") {
            toPoint = { "x": toNode["x"] + toNode["width"] / 2, "y": toNode["y"] + toNode["height"] };
          } else if (toSide == "left") {
            toPoint = { "x": toNode["x"], "y": toNode["y"] + toNode["height"] / 2 };
          } else if (toSide == "right") {
            toPoint = { "x": toNode["x"] + toNode["width"], "y": toNode["y"] + toNode["height"] / 2 };
          }
          distances.push({
            "fromSide": fromSide,
            "toSide": toSide,
            "distance": (toPoint.x - fromPoint.x) ** 2 + (toPoint.y - fromPoint.y) ** 2
          });
        }
      }
      distances = distances.sort(function(a, b) {
        return a.distance - b.distance;
      });
      edge["from"]["side"] = distances[0]["fromSide"];
      edge["to"]["side"] = distances[0]["toSide"];
      edge.render();
    }
    canvas.requestSave();
  }
};
