/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DiscordExportPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/modal.ts
var import_obsidian = require("obsidian");

// src/processor.ts
var FIRST_PARA_PREFIX = "_ _ _ _ ";
var OTHER_PARA_PREFIX = "    ";
function stripFrontmatter(text) {
  return text.replace(/^---\n[\s\S]*?\n---\n?/, "").trimStart();
}
function stripIgnoreBlocks(text) {
  return text.replace(/\{[\s\S]*?\}/g, "").replace(/[ \t]{2,}/g, " ").replace(/\n{3,}/g, "\n\n").trim();
}
function stripTags(text) {
  return text.replace(/^(#[\w/-]+\s*)+$/gm, "").replace(/\n{3,}/g, "\n\n").trim();
}
function stripHorizontalRules(text) {
  return text.replace(/^---$/gm, "").replace(/\n{3,}/g, "\n\n").trim();
}
function cleanText(text) {
  let t = stripFrontmatter(text);
  t = stripIgnoreBlocks(t);
  t = stripTags(t);
  t = stripHorizontalRules(t);
  return t;
}
function packSegment(segment, charLimit, mode) {
  const lines = segment.split("\n");
  const chunks = [];
  let currentLines = [];
  let currentLength = 0;
  let isFirstInChunk = true;
  function applyPrefix(raw) {
    if (mode !== "indent" || raw.trim().length === 0) return raw;
    return (isFirstInChunk ? FIRST_PARA_PREFIX : OTHER_PARA_PREFIX) + raw;
  }
  function flush() {
    let end = currentLines.length;
    while (end > 0 && currentLines[end - 1].trim() === "") end--;
    if (end > 0) chunks.push(currentLines.slice(0, end).join("\n"));
    currentLines = [];
    currentLength = 0;
    isFirstInChunk = true;
  }
  for (const raw of lines) {
    const isBlank = raw.trim().length === 0;
    const candidate = applyPrefix(raw);
    const sep = currentLines.length > 0 ? 1 : 0;
    if (!isBlank && currentLines.length > 0 && currentLength + candidate.length + sep > charLimit) {
      flush();
    }
    const final = applyPrefix(raw);
    const s = currentLines.length > 0 ? 1 : 0;
    currentLines.push(final);
    currentLength += final.length + s;
    if (!isBlank) isFirstInChunk = false;
  }
  flush();
  return chunks;
}
function processNote(rawText, charLimit, mode) {
  const text = cleanText(rawText.replace(/\r\n/g, "\n"));
  const segments = text.split(/^[ \t]*\+\+\+[ \t]*$/m).map((s) => s.trim()).filter((s) => s.length > 0);
  return segments.flatMap((segment) => packSegment(segment, charLimit, mode));
}

// src/modal.ts
var DiscordExportModal = class extends import_obsidian.Modal {
  constructor(app, rawText, settings) {
    super(app);
    this.copiedChunks = /* @__PURE__ */ new Set();
    this.rawText = rawText;
    this.settings = settings;
    this.currentMode = settings.defaultMode;
    this.currentLimit = settings.charLimit;
  }
  onOpen() {
    this.modalEl.addClass("de-modal");
    this.render();
  }
  onClose() {
    this.contentEl.empty();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("de-content");
    const header = contentEl.createDiv({ cls: "de-header" });
    header.createEl("span", { text: "Discord Export", cls: "de-title" });
    const controls = header.createDiv({ cls: "de-controls" });
    const modeGroup = controls.createDiv({ cls: "de-seg-group" });
    modeGroup.createEl("span", { text: "Mode", cls: "de-seg-label" });
    const modeBtns = modeGroup.createDiv({ cls: "de-seg-btns" });
    for (const [val, label] of [["indent", "Indent"], ["splitter", "Splitter"]]) {
      const btn = modeBtns.createEl("button", {
        text: label,
        cls: "de-seg-btn" + (this.currentMode === val ? " is-active" : "")
      });
      btn.addEventListener("click", () => {
        this.currentMode = val;
        this.render();
      });
    }
    const limitGroup = controls.createDiv({ cls: "de-seg-group" });
    limitGroup.createEl("span", { text: "Limit", cls: "de-seg-label" });
    const limitBtns = limitGroup.createDiv({ cls: "de-seg-btns" });
    for (const [val, label] of [[2e3, "2 000"], [4e3, "4 000"]]) {
      const btn = limitBtns.createEl("button", {
        text: label,
        cls: "de-seg-btn" + (this.currentLimit === val ? " is-active" : "")
      });
      btn.addEventListener("click", () => {
        this.currentLimit = val;
        this.render();
      });
    }
    const chunks = processNote(this.rawText, this.currentLimit, this.currentMode);
    if (chunks.length === 0) {
      const empty = contentEl.createDiv({ cls: "de-empty" });
      empty.createEl("span", { text: "Nothing to export \u2014 the note appears to be empty." });
      return;
    }
    const list = contentEl.createDiv({ cls: "de-list" });
    chunks.forEach((chunk, index) => {
      const pct = chunk.length / this.currentLimit;
      const status = pct >= 1 ? "overflow" : pct >= 0.9 ? "warning" : "safe";
      const statusLabel = { safe: "Safe", warning: "Near limit", overflow: "Overflow" }[status];
      const card = list.createDiv({ cls: "de-card" });
      if (this.copiedChunks.has(index)) card.addClass("is-copied");
      const cardHead = card.createDiv({ cls: "de-card-head" });
      const left = cardHead.createDiv({ cls: "de-card-left" });
      left.createEl("span", { text: String(index + 1).padStart(2, "0"), cls: "de-chunk-num" });
      left.createEl("span", { text: statusLabel, cls: `de-badge de-badge--${status}` });
      const right = cardHead.createDiv({ cls: "de-card-right" });
      right.createEl("span", {
        text: `${chunk.length.toLocaleString()} / ${this.currentLimit.toLocaleString()}`,
        cls: "de-char-count"
      });
      const copyBtn = right.createEl("button", { cls: "de-copy-btn" });
      const alreadyCopied = this.copiedChunks.has(index);
      copyBtn.setText(alreadyCopied ? "\u2713 Copied" : "Copy");
      if (alreadyCopied) copyBtn.addClass("is-copied");
      copyBtn.addEventListener("click", async () => {
        await navigator.clipboard.writeText(chunk);
        this.copiedChunks.add(index);
        card.addClass("is-copied");
        copyBtn.addClass("is-copied");
        copyBtn.setText("\u2713 Copied");
      });
      const preview = card.createDiv({ cls: "de-preview" });
      preview.textContent = chunk;
    });
    const footer = contentEl.createDiv({ cls: "de-footer" });
    footer.createEl("span", {
      text: `${chunks.length} chunk${chunks.length !== 1 ? "s" : ""}`,
      cls: "de-footer-chunks"
    });
    footer.createEl("span", {
      text: `${this.rawText.length.toLocaleString()} chars in note`,
      cls: "de-footer-total"
    });
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  charLimit: 2e3,
  defaultMode: "indent"
};
var DiscordExportSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Character limit").setDesc("Maximum characters per Discord message. Use 4000 if you have Nitro.").addDropdown(
      (dropdown) => dropdown.addOption("2000", "2000 (default)").addOption("4000", "4000 (Nitro)").setValue(String(this.plugin.settings.charLimit)).onChange(async (value) => {
        this.plugin.settings.charLimit = Number(value);
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Default mode").setDesc(
      "Indent mode adds paragraph indentation for creative writing. Splitter mode just splits the text into chunks with no indentation."
    ).addDropdown(
      (dropdown) => dropdown.addOption("indent", "Indent (creative writing)").addOption("splitter", "Splitter (chunks only)").setValue(this.plugin.settings.defaultMode).onChange(async (value) => {
        this.plugin.settings.defaultMode = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var DiscordExportPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "open-discord-export",
      name: "Export note to Discord",
      editorCallback: (editor, view) => {
        const rawText = editor.getValue();
        new DiscordExportModal(this.app, rawText, this.settings).open();
      }
    });
    this.addSettingTab(new DiscordExportSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */